### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by MetaMmodern** [arqex/react-interactable#5]
There is a problem when using latest React i think. How can I make it work?
(dependecies are on left, usage--center, behaviour--on right)
![image](https://user-images.githubusercontent.com/42899786/101289571-fc129400-3805-11eb-9e79-ea8e8c76a492.png)

**Comment by MetaMmodern** [comment]
okay, I figured out that the latest version to work with is react 16.14. other dependencies do not influence the appearance of error.
![image](https://user-images.githubusercontent.com/42899786/101289980-4432b600-3808-11eb-8611-6f712fe2487b.png)
